# Generated by Django 5.1.15 on 2026-07-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', '-start_time']},
        ),
    ]
