# Generated by Django 5.1.15 on 2026-07-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_add_child_and_volunteeropportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='volunteers.volunteeropportunity'),
        ),
    ]
