# Generated by Django 5.1.15 on 2026-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
